[package]
name = "packet-generator"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[[bin]]
name = "rs-udp-packet-generator"
path = "src/main.rs"

[dependencies]
udp-sender = { path = "../udp-sender" }
clap = { version = "4.6", features = ["derive"] }
anyhow = "1.0"
